
spring.application.name=ai-document-qa

# =========================
# Gemini - Chat Model
# =========================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash

# =========================
# Ollama - Embedding Model
# =========================
spring.ai.ollama.base-url=http://localhost:11434

spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=embeddinggemma

# IMPORTANT:
# Use Gemini for Chat, NOT Ollama
spring.ai.model.chat=google-genai